version: '3.8'
services:
  timescaledb:
    image: timescale/timescaledb:latest-pg16
    container_name: timescaledb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: mytimescaledb
    volumes:
      - ../../data:/var/lib/postgresql/data
