name: CI Pipeline - SOEP

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y g++ cmake libcurl4-openssl-dev libssl-dev libpqxx-dev libjsoncpp-dev

      - name: Build with CMake
        run: |
          mkdir -p build
          cd build
          cmake ..
          cmake --build .

      - name: Build Docker image
        run: |
          docker build -t soep .
